### ISSUE TITLE
Arduino Uno:  i2c_t3.h missing

### ISSUE THREAD

**Issue by jonathanrjpereira** [nox771/i2c_t3#10]
```
#include "i2c_t3.h"  // I2C library

                                    ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.
```
Can you just include these files in your repository?

**Comment by nox771** [comment]
??? i2c_t3.h is in the repo:
https://github.com/nox771/i2c_t3/blob/master/i2c_t3.h

"Error compiling for board Arduino/Genuino Uno."
This library doesn't work for AVR boards like the Uno.  It only works for Teensy 3.x boards (ARM).

**Comment by tonton81** [comment]
lol... :)

**Comment by jonathanrjpereira** [comment]
Damn. I have literally scrolled through the first 2 page results of Google for the MPU 9250. All of them have some sort of compilation error or are just incompatible with the Arduino UNO.
