### ISSUE TITLE
Are asynchronous callbacks called from interrupt? (documentation)

### ISSUE THREAD

**Issue by bmegli** [nox771/i2c_t3#22]
Hi @nox771,

First, thank you for this awesome library.

Are the asynchronous background transfer callbacks for
- `onTransmitDone`
- `onReqFromDone`
- `onError`

...called from the interrupt handler?

I suppose they have to, at least when initiating background transfer with:
- `sendRequest`
- `sendTransmission`

**Comment by nox771** [comment]
Yes that is correct, the interrupt handler will call those functions upon completion (only if they are setup).  

There is an example "basic_master_callback" which shows how to setup the functions.

**Comment by bmegli** [comment]
Thanks!

Yes, I know the example and already have working implementation.
