### ISSUE TITLE
Wire.end() not implemented

### ISSUE THREAD

**Issue by utacc** [nox771/i2c_t3#27]
I'm trying to communicate to a hybrid I2C/SPI device, which occasionally needs to be powered down. I have it isolated on its very own I2C bus, with nothing else on it, specifically so I can drop the I2C lines (in tests, the I2C lines actually (partially) power the device if I2C isn't end()-ed, SDA and SCL then get turned into outputs, and then set LOW). 
In the Wire library, the interrupts get shut off, and the pins get unassigned. Should we do that manually with this library, or are there plans to implement end()?
2/26/19: I implemented Wire.end(). No worries.

**Comment by nox771** [comment]
Sorry, been a bit busy.  If you think it is generic enough and want to share, then you can upload the code or do a pull request and I can incorporate it into the main repo.

**Comment by utacc** [comment]
Lol I don't remember how, unfortunately,  my git skills are very rusty. I
also think it should be tested. It works for me, in my application, but
that's a low bar.
I can send you a diff delta too.

**Comment by utacc** [comment]
It should be generic enough, though. I wanted it to be a reasonable
facsimile of the same function from the original Wire library. It seems to
work as well as the original does, electrically.

**Comment by nox771** [comment]
Sure whatever you have is ok.  You can email it direct to me if you want, my email is in the i2c_t3.h file.  It may take a while for me to add anything, but I'll try to get it done.
